wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: huggingface
    huggingface_version: 4.26.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1671853023.924441
    t:
      1:
      - 11
      - 12
      - 45
      - 49
      - 55
      2:
      - 1
      - 11
      - 12
      - 45
      - 49
      - 55
      3:
      - 23
      4: 3.10.6
      5: 0.13.1
      6: 4.26.0.dev0
      8:
      - 5
